### ISSUE TITLE
AZERTY Support

### ISSUE THREAD

**Issue by cheznewa** [larsbrinkhoff/terminal-simulator#40]
Hi/Hello, Is Possible To Add AZERTY Keyboard For French User?

**Comment by larsbrinkhoff** [comment]
Yes, that would be possible.  As far as I know, SDL makes it difficult or impossible to detect the keyboard mapping of the host operating system, so AZERTY would have to be manually selected.  But other than that, it should be straight-forward.

I don't have any free time at the moment.  I invite you to make a pull request.

**Comment by cheznewa** [comment]
I Can't Write In C, Too Hard For Me.
