### ISSUE TITLE
Issues on my PI 4

### ISSUE THREAD

**Issue by ronaldlw** [larsbrinkhoff/terminal-simulator#41]
I've just installed this as follow:

- installed the latest version of the Raspberry OS Lite on my PI 4
- installed the SDL2 dev libraries
- installed git
- checked out the repo
- cd vt100
- make
- ran the emulator like so (without -Q and -N4 the system basically just locks up and I have to power cycle) ./vt100 -Q -N4 bash

I end up with screens like this:
![0923221917](https://user-images.githubusercontent.com/64380117/192072171-6742f57a-2d40-413c-b131-e48bca4d1952.jpg)

![0923221918](https://user-images.githubusercontent.com/64380117/192072177-5ae56464-1854-4e15-87b8-1184f39c94ef.jpg)

Note the video is running off the left of the screen and for some reason there's a mouse cursor that shows up while it's running.

I'm confused on so many levels, lol   I thought this project was specifically created to use with the 2/3 scale VT100 project which uses a PI4, so I'm surprised it doesn't seem to work at all without disabling openGL and lowering the refresh rate so low.  And I'm surprised the PI4 has any difficulty at all emulating an 8080 processor.

Anyway, any suggestions on how to get this working better would be much appreciated!

**Comment by ronaldlw** [comment]
I found -f fixes the issue with text off the screen and the presence of the mouse cursor!

**Comment by larsbrinkhoff** [comment]
It looks like without -f the window is too large for the display you have.

Yes, the project is primarily targeting the VT100 replica.  But it turns out even a Raspberry Pi 4 isn't fast enough to render the video at full speed.  Possibly there could be a bottleneck in the SDL library, not sure.  Emulating the 8080 is no problem, just the video.

**Comment by ronaldlw** [comment]
what resolution is it trying to render at by default?  I have the 8" 1024 x 768 lcd display from Digikey mentioned in the VT100 replica project.

**Comment by larsbrinkhoff** [comment]
The default is 810x490.  So if you don't use the `-2` option, that would not explain why the window doesn't fit.

**Comment by larsbrinkhoff** [comment]
Solution or workaround: use -f.
