### ISSUE TITLE
Is there a way to change the color of the text?

### ISSUE THREAD

**Issue by ronaldlw** [larsbrinkhoff/terminal-simulator#42]
Can we make a green or amber monitor?

**Comment by larsbrinkhoff** [comment]
That should be quite easy.  But I'm rather pressed for time now, so I'm looking for contributors to submit a pull request.

**Comment by ronaldlw** [comment]
i found that by twiddling with this line I was able to change to amber and green:
https://github.com/larsbrinkhoff/terminal-simulator/blob/d5e3ae99850865ccf52c7285d32eedc89442df63/vt100/render.c#L53

  u32 x = data->brightness;
  x = 255 * (31 - (x & 0x1F)) / 31; 

  lit = x << 16 | x << 8 | x;  //original, white
  lit = x << 16 | x * 8 / 10 << 8 ;  // amber
  lit = x << 8 | x * 2 / 10 ;  // green

![1005221812b](https://user-images.githubusercontent.com/64380117/194180917-eea70a18-a646-4407-bbf4-7c53d5d556c0.jpg)

**Comment by larsbrinkhoff** [comment]
Problem solved, then.
